{{- $fullName := include "estafette-ci-web.fullname" . -}}
{{- $labels := include "estafette-ci-web.labels" . -}}
{{- range .Values.extraSecrets -}}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ $fullName }}.{{ .key }}
  labels:
    {{- $labels | nindent 4 }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 -}}
  {{- end }}
{{- if .data }}
data:
  {{- range $key, $value := .data }}
    {{ $key }}: {{ $value | toString | b64enc }}
  {{- end }}
{{- end }}
{{- end }}